### ISSUE TITLE
ConstraintViolationException is swallowed then server responds 200

### ISSUE THREAD

**Issue by rafanoronha** [garcia-jj/vraptor-plugin-hibernate4#18]
Please help me understand where this issue should be addressed.

Sometimes database errors on my app are swallowed.
This is really critical 'cause my app can't go live under the risk of failed operations not be reported to the end user.

The problem occurs on 1.5.0, vraptor 3.5.3.

Here goes the stacktrace gathered from one of those situations.
Please note that even the error being printed it didn't produces any status code other than 200.

```
14-03-03 16:46:34,719 [WARN] org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 23503
14-03-03 16:46:34,722 [ERROR] org.hibernate.engine.jdbc.spi.SqlExceptionHelper - ERRO: inserþÒo ou atualizaþÒo em tabela "xpto" viola restriþÒo de chave estrangeira "fkd8e66fbeb6d3c689"
  Detail: Chave (xpto_id)=(999) nÒo estß presente na tabela "xpto".
/xpto/20
org.hibernate.exception.ConstraintViolationException: could not execute statement
    at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129)
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
    at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
    at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:190)
    at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:96)
    at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:58)
    at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3032)
    at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3556)
    at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:97)
    at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:480)
    at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:191)
    at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:175)
    at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:210)
    at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:324)
    at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:288)
    at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:194)
    at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
    at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:209)
    at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:194)
    at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:114)
    at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)
    at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:680)
    at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:672)
    at org.hibernate.engine.spi.CascadingActions$5.cascade(CascadingActions.java:235)
    at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:352)
    at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:295)
    at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:161)
    at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:381)
    at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:321)
    at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:298)
    at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:161)
    at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:118)
    at org.hibernate.event.internal.AbstractFlushingEventListener.cascadeOnFlush(AbstractFlushingEventListener.java:167)
    at org.hibernate.event.internal.AbstractFlushingEventListener.prepareEntityFlushes(AbstractFlushingEventListener.java:158)
    at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:91)
    at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:55)
    at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1218)
    at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:421)
    at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
    at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)
    at br.com.caelum.vraptor.plugin.hibernate4.HibernateTransactionInterceptor.intercept(HibernateTransactionInterceptor.java:53)
    at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
    at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
    at br.com.caelum.vraptor.core.LazyInterceptorHandler.execute(LazyInterceptorHandler.java:61)
    at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
    at br.com.caelum.vraptor.interceptor.ResourceLookupInterceptor.intercept(ResourceLookupInterceptor.java:69)
    at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:54)
    at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:54)
    at br.com.caelum.vraptor.core.EnhancedRequestExecution.execute(EnhancedRequestExecution.java:44)
    at br.com.caelum.vraptor.VRaptor$1.insideRequest(VRaptor.java:91)
    at br.com.caelum.vraptor.ioc.guice.GuiceProvider.provideForRequest(GuiceProvider.java:82)
    at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:88)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
    at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
    at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: org.postgresql.util.PSQLException: ERRO: inserþÒo ou atualizaþÒo em tabela "xpto" viola restriþÒo de chave estrangeira "fkd8e66fbeb6d3c689"
Detail: Chave (xpto_id)=(999) nÒo estß presente na tabela "xpto".
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:334)
    at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:147)
    at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:187)
            ... 65 more
```

**Comment by lucascs** [comment]
The problem is: if you wrote anything to response, there is no way of changing the status code, because it's the first thing written to response.

If you follow a simple pattern: Always redirect after a POST (changing the database), you can solve it with this interceptor: https://github.com/caelum/vraptor-hibernate/blob/master/src/main/java/br/com/caelum/vraptor/hibernate/HibernateTransactionInterceptor.java

note the redirectListener at the end of the file. It will try to commit the transaction right before the redirect, so the constraint violation will prevent the redirect.

We should change the respective interceptor from this plugin with the same code as the interceptor of the link. Do you wanna do this and send a pull request?

**Comment by rafanoronha** [comment]
@lucascs 
Thanks for the explanation.
My app is mainly a JSON API so I'm afraid the redirect approach wouldn't fit to us.
All transaction actions go through an json interceptor (forked from this: [1])

[1] https://github.com/luizsignorelli/vraptor-gson-serializer/blob/master/src/main/java/br/com/caelum/vraptor/serialization/gson/interceptor/JsonInterceptor.java

**Comment by rafanoronha** [comment]
@lucascs 
Does that response writing happens after I started to interact with the Result API?
Maybe an interceptor executing before that would check if transaction was rolled back and then throw an error?

**Comment by rafanoronha** [comment]
Actually from the stacktrace I would say that my json interceptor didn't execute so who is writing stuff to the response?

**Comment by lucascs** [comment]
how is your controller method?

if it's like this:

``` java
@Json
public SomeObject method(...) {
    // no result here
    return someObject;
}
```

This interceptor would work if it executes right after the transaction commit.

I believe changing it's intercept to this would work:

``` java
public void intercept(...) {
    result.nothing(); // just to prevent forward to default view
    stack.next(...);
    result.use(json())....
}
```

**Comment by rafanoronha** [comment]
@lucascs 
I was wrong about the execution order of the interceptors, the serialization actually happens before the commit in the way the transaction interceptors currently works.
My method is like the former.

I've built a snapshot of this plugin where I configure it to run just after ExecuteMethodInterceptor and it seems to solve my issue.

Still I'm not sure this plugin or even vraptor core shouldn't do anything else about it.
Maybe a safer vraptor code might write to response output closer to the end of the execution pipeline instead of current approach where views code are writing directly to it?
I'm also considering to increase response buffer size to check if then any given exception would raise a 500 error.

**Comment by lucascs** [comment]
Problem is serialization and transaction handling are unrelated... It's strange for the framework to associate the two in a single thing. But maybe a lazy feature for serialization would solve your problems.

Something like:

``` java
result.use(json()).lazy()....
```

which will only write to response after everything happens. Even so, it won't solve all corner cases =/

try to do something like:

```
@Component
public class LazySerialization {
     private Serializer serializer;

     public void delay(Serializer serializer) {
        this.serializer = serializer;
     }
    public void serialize() {
        if (serializer != null) serializer.serialize();
    }
}
```

on controller:

``` java
serializer.delay(result.use(json()).from(object)); // don't call serialize!
```

and add this interceptor:

``` java
@Intercepts(before=XXXTransactionInterceptor.class)
public class LazySerializationInterceptor implements Interceptor {
     //inject lazySerialization on constructor

    public void intercept(...) {
        stack.next()
        lazySerialization.serialize();
    }
}
```

see if this solves your problem

**Comment by rafanoronha** [comment]
@lucascs 
Yep, that should do the trick.

I've also found out that GsonSerializer is flushing the response writer (XStream's implementation seems to do that too).
If flush don't get called that later exception raises the 500 error, provided that the json body size isn't bigger than the response buffer size.
Does it make sense to work on a pull request where flush stop being called? Servlet containers already ensure that the response is properly flushed.

I still do think vraptor should provide a safer ground for different scenarios (given the risk, serializers shouldn't write directly to response OMHO). Does it sound reasonable?

**Comment by garcia-jj** [comment]
I think that `GsonSerializer` shouldn't call `flush` because 1) appserver already do this 2) if you don't create stream you can't flush neither close.

**Comment by lucascs** [comment]
`.serialize()` writes into response. It automatically commits the response. There is nothing we can do about it, besides postponing the write.

I don't remember why the flush is being called on serializer, maybe the git history can tell us about it.

**Comment by garcia-jj** [comment]
This `fush` exists since the 1st version of Gson serializer.

**Comment by lucascs** [comment]
So can you send a PR removing this two lines, please? 
https://github.com/caelum/vraptor/blob/master/vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/GsonSerializer.java#L154-L155

**Comment by rafanoronha** [comment]
@lucascs yep, it's all about postponing the write.
My point is, couldn't `serialize()` write to a temporary stream which is later copied to response only if nothing goes wrong?

**Comment by rafanoronha** [comment]
@lucascs about the pull request, removing those two lines breaked the tests, not sure how to fix them.

**Comment by garcia-jj** [comment]
What's the error? Since tests are not managed by servlet, you need to flush manually. But the error message can show more details about.

**Comment by rafanoronha** [comment]
@garcia-jj yep I manually called `flush` and `close` but `toByteArray` always gives an empty string for some reason.

**Comment by lucascs** [comment]
If you use StringWriter and call toString() after the call, it should give the written json, without the need of a flush or a close.
